FROM golang:1.16 AS builder
WORKDIR /go/src/gin-api/build/
RUN go get -d -v golang.org/x/net/html
COPY server.go .
COPY go.mod .
COPY go.sum .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
EXPOSE 8080
WORKDIR /root/
COPY --from=builder /go/src/gin-api/build/app .
CMD ["./app"]
